export const ApiUrls = {
  login: "/api/v1/login",
  register: "/api/v1/register",
  logout: "/api/v1/logout",
  authorization: "/api/v1/authorization",
  healthcheck: "/api/v1/healthcheck",
  ping: "/api/v1/ping",
  databases: "/api/v1/databases",
  memory: "/api/v1/memory",
  about: "/api/v1/about",
  documentation: "/api/v1/documentation",
  statistics: "/api/v1/statistics",
  metrics: "/api/v1/metrics",
  debug: "/api/v1/debug",
  logs: "/api/v1/logs",
  usersProfile: "/api/v1/users/profile",
  userById: (userId: string) => `/api/v1/users/${userId}`,
  usersStatistics: "/api/v1/users/statistics",
  usersStatisticsAll: "/api/v1/users/statistics/all",

  fields: "/api/v1/fields",
  fieldById: (id: number) => `/api/v1/fields/${id}`,
  fieldsDistricts: "/api/v1/fields/districts",
  fieldsDistrictsById: (id: number) => `/api/v1/fields/districts/${id}`,
  staff: "/api/v1/staff",
  staffById: (id: number) => `/api/v1/staff/${id}`,
  fieldsAssign: "/api/v1/fields/assign",
  fieldsAssignById: (id: number) => `/api/v1/fields/assign/${id}`,
  assignments: "/api/v1/assignments",
  assignmentById: (id: number) => `/api/v1/assignments/${id}`,
  animals: "/api/v1/animals",
  animalById: (id: number) => `/api/v1/animals/${id}`,
  animalTypes: "/api/v1/animals/types",
  map: "/api/v1/map",
  mapFieldsmap: "/api/v1/map/fieldsmap",
  mapDistricts: "/api/v1/map/districts",

  financialAccount: "/api/v1/financial/account",
  financialTransactions: "/api/v1/financial/transactions",
  financialTransactionById: (id: number) =>
    `/api/v1/financial/transactions/${id}`,
  financialStats: "/api/v1/financial/stats",
  financialReport: "/api/v1/financial/report",
  financialTransfer: "/api/v1/financial/transfer",
  financialMarketplaceStats: "/api/v1/financial/marketplace-stats",
  financialAccountsAll: "/api/v1/financial/accounts/all",
  financialAccountsBalance: "/api/v1/financial/accounts/balance",
  marketplaceOffers: "/api/v1/marketplace/offers",
  marketplaceOfferById: (offerId: number) =>
    `/api/v1/marketplace/offers/${offerId}`,
  marketplaceMyOffers: "/api/v1/marketplace/my-offers",
  marketplaceBuy: "/api/v1/marketplace/buy",
  marketplaceTransactions: "/api/v1/marketplace/transactions",
  contact: "/api/v1/contact",
  alerts: "/api/v1/alerts",
  alertsHistory: "/api/v1/alerts/history",
  alertsUpcoming: "/api/v1/alerts/upcoming",
  featureFlags: "/api/v1/feature-flags",
  featureFlagsReset: "/api/v1/feature-flags/reset",
} as const;
